CREATE TYPE REPORT_INFO AS OBJECT(
				INFO_NO NUMBER,
				INFO_NID VARCHAR2(20),
				REPORTED_DATE DATE,
				DESCRIPTION VARCHAR2(50),
				DIV_ID NUMBER
);
/ 
CREATE TYPE REPORT_TABLE IS TABLE OF REPORT_INFO;
/

CREATE OR REPLACE 
FUNCTION GenerateReport(PARA NUMBER)
		RETURN REPORT_TABLE PIPELINED IS
		REPORT_ROW REPORT_INFO;
		DESCR VARCHAR2(50);
		DESCR2 VARCHAR2(50);
	BEGIN
		IF(PARA = 1) THEN
			FOR R IN (SELECT LICENSE_NO,DRIVER_NID,VALIDITY_DATE,DIV_ID FROM LICENSE 
								WHERE VALIDITY_DATE < SYSDATE)
			LOOP
				DESCR := 'LICENSE VALIDITY IS OVER';
				PIPE ROW(REPORT_INFO(R.LICENSE_NO,R.DRIVER_NID,R.VALIDITY_DATE,DESCR,R.DIV_ID));
			END LOOP;
		
		ELSIF(PARA = 2) THEN
			FOR R IN (SELECT TAX_VALIDITY_DATE, FITNESS_VALIDITY_DATE, REG_NO, OWNER_NID,
								DIV_ID FROM VEHICLE)
			LOOP
				IF(R.TAX_VALIDITY_DATE < SYSDATE) THEN
					 DESCR := 'TAX VALIDITY IS OVER';
				PIPE ROW(REPORT_INFO(R.REG_NO,R.OWNER_NID,R.TAX_VALIDITY_DATE,DESCR,R.DIV_ID));
				END IF;
				IF(R.FITNESS_VALIDITY_DATE < SYSDATE) THEN
					 DESCR2 := 'FITNESS VALIDITY IS OVER';
				PIPE ROW(REPORT_INFO(R.REG_NO,R.OWNER_NID,R.FITNESS_VALIDITY_DATE,DESCR2,R.DIV_ID));
				END IF;
			END LOOP;
		END IF;
END;
/
SELECT * from TABLE(GenerateReport(1));
SELECT * from TABLE(GenerateReport(2));
