
CREATE OR REPLACE TRIGGER BeforeVehicleOwnerUpdate
	BEFORE UPDATE
	OF OWNER_NID
	ON VEHICLE
	FOR EACH ROW
DECLARE

BEGIN
	if (:OLD.OWNER_NID <> :NEW.OWNER_NID) then

		UPDATE OWNER o
		SET o.NUMBER_OF_VEHICLES = o.NUMBER_OF_VEHICLES - 1
		WHERE o.OWNER_NID = :OLD.OWNER_NID;

		DELETE FROM OWNER O WHERE O.OWNER_NID = :OLD.OWNER_NID AND O.NUMBER_OF_VEHICLES = 0;

		UPDATE OWNER o
		SET o.NUMBER_OF_VEHICLES = o.NUMBER_OF_VEHICLES + 1
		WHERE o.OWNER_NID = :NEW.OWNER_NID;
	end if;


END;
/	