CREATE OR REPLACE TRIGGER PAYMENT_CONSEQ
				AFTER INSERT ON PAYMENT
				FOR EACH ROW
DECLARE
				HISTORYNUM NUMBER;
BEGIN
				HISTORYNUM := :NEW.HISTORY_NO;
				IF(:NEW.TYPE = 'Penalty') THEN
					UPDATE PENALTYHISTORY
					SET Status = 'Paid' WHERE ENTRY_NO = HISTORYNUM;
				ELSIF(:NEW.TYPE = 'Vehicle Service') THEN
					UPDATE VEHICLESERVICEHISTORY
					SET Status = 'Paid' WHERE ENTRY_NO = HISTORYNUM;
				ELSIF(:NEW.TYPE = 'License Service') THEN
					UPDATE LICENSESERVICEHISTORY
					SET Status = 'Paid' WHERE ENTRY_NO = HISTORYNUM;
				ELSE 
					DBMS_OUTPUT.PUT_LINE('WRONG INPUT');
				END IF;

END;
/