insert into "Division"  values (1, 'Baoluan');
insert into "Division"  values (2, 'Volzhskiy');
insert into "Division"  values (3, 'Xinying');
insert into "Division"  values (4, 'Jiangjiazui');
insert into "Division"  values (5, 'Papetoai');
insert into "Division"  values (6, 'Lonpao Dajah');
insert into "Division"  values (7, 'Dailekh');
insert into "Division"  values (8, 'Zaraza');
insert into "Division"  values (9, 'Eybens');
insert into "Division"  values (10, 'Lotoshino');
insert into "Division"  values (11, 'Antalaha');
insert into "Division"  values (12, 'Phutthaisong');
insert into "Division"  values (13, 'Chaupimarca');
insert into "Division"  values (14, 'Heilbronn');
insert into "Division"  values (15, 'Qal‘eh-ye Khvājeh');
insert into "Division"  values (16, 'Lityn');
insert into "Division"  values (17, 'Trieste');
insert into "Division"  values (18, 'Whittier');
insert into "Division"  values (19, 'Baih');
insert into "Division"  values (20, 'Lin’an');
insert into "Division"  values (21, 'Opařany');
insert into "Division"  values (22, 'Sulengwaseng');
insert into "Division"  values (23, 'Felgueiras');
insert into "Division"  values (24, 'Itinga');
insert into "Division"  values (25, 'Clearwater');
insert into "Division"  values (26, 'Wydminy');
insert into "Division"  values (27, 'Stockholm');
insert into "Division"  values (28, 'Huainan');
insert into "Division"  values (29, 'Quva');
insert into "Division"  values (30, 'Levallois-Perret');
insert into "Division"  values (31, 'Eséka');
insert into "Division"  values (32, 'Toulon');
insert into "Division"  values (33, 'HanHuang');
insert into "Division"  values (34, 'Knoxville');
insert into "Division"  values (35, 'La Jagua de Ibirico');
insert into "Division"  values (36, 'Longwood');
insert into "Division"  values (37, 'Schiedam postbusnummers');
insert into "Division"  values (38, 'Lanta Timur');
insert into "Division"  values (39, 'Wailebe');
insert into "Division"  values (40, 'Tempursari Wetan');
insert into "Division"  values (41, 'Daqiao');
insert into "Division"  values (42, 'Bontoc');
insert into "Division"  values (43, 'Benito Juarez');
insert into "Division"  values (44, 'Livramento do Brumado');
insert into "Division"  values (45, 'Dougang');
insert into "Division"  values (46, 'Wulongshan');
insert into "Division"  values (47, 'Liljendal');
insert into "Division"  values (48, 'Mlandizi');
insert into "Division"  values (49, 'Suez');
insert into "Division"  values (50, 'Palma De Mallorca');
insert into "Division"  values (51, 'Kissónerga');
insert into "Division"  values (52, 'Gentilly');
insert into "Division"  values (53, 'Inuyama');
insert into "Division"  values (54, 'Freiburg im Breisgau');
insert into "Division"  values (55, 'Perches');
insert into "Division"  values (56, 'Barrio San Luis');
insert into "Division"  values (57, 'Totolan');
insert into "Division"  values (58, 'San Juan Bautista');
insert into "Division"  values (59, 'Comagascas');
insert into "Division"  values (60, 'Al Ḩaffah');
insert into "Division"  values (61, 'Tampa');
insert into "Division"  values (62, 'Baru');
insert into "Division"  values (63, 'Cayambe');
insert into "Division"  values (64, 'Ochër');
insert into "Division"  values (65, 'Capâo Bonito');
insert into "Division"  values (66, 'La Cañada');
insert into "Division"  values (67, 'Caen');
insert into "Division"  values (68, 'Zicheng');
insert into "Division"  values (69, 'Iksha');
insert into "Division"  values (70, 'Rakhmanovo');
insert into "Division"  values (71, 'Yaguarón');
insert into "Division"  values (72, 'Surin');
insert into "Division"  values (73, 'Narsingdi');
insert into "Division"  values (74, 'Malá Strana');
insert into "Division"  values (75, 'San Pedro de Atacama');
insert into "Division"  values (76, 'Yoiqag');
insert into "Division"  values (77, 'Nu’erbage');
insert into "Division"  values (78, 'Novorossiysk');
insert into "Division"  values (79, 'Bururi');
insert into "Division"  values (80, 'Kudowa-Zdrój');
insert into "Division"  values (81, 'Besançon');
insert into "Division"  values (82, 'Eláteia');
insert into "Division"  values (83, 'Jāndiāla Sher Khān');
insert into "Division"  values (84, 'Kertasari');
insert into "Division"  values (85, 'Jomboy');
insert into "Division"  values (86, 'Tyazhinskiy');
insert into "Division"  values (87, 'Tymbark');
insert into "Division"  values (88, 'Sumbersewu');
insert into "Division"  values (89, 'Trawniki');
insert into "Division"  values (90, 'Apengjiang');
insert into "Division"  values (91, 'Medalem');
insert into "Division"  values (92, 'Karengan');
insert into "Division"  values (93, 'Līvāni');
insert into "Division"  values (94, 'Saint-Jean-de-Monts');
insert into "Division"  values (95, 'Ivanava');
insert into "Division"  values (96, 'Qingu');
insert into "Division"  values (97, 'Krajan Dua Putukrejo');
insert into "Division"  values (98, 'Torkanivka');
insert into "Division"  values (99, 'Toledo');
insert into "Division"  values (100, 'Alcanena');
