/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.2.0.5.0

Source Server         : TransportManagementSystem
Source Server Version : 110200
Source Host           : :1521
Source Schema         : TRANSPORTMANAGEMENT

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2018-01-01 21:58:21
*/


-- ----------------------------
-- Table structure for DIVISION
-- ----------------------------
--DROP TABLE TRANSPORTMANAGEMENT.DIVISION;
CREATE TABLE TRANSPORTMANAGEMENT.DIVISION (
DIV_ID NUMBER NOT NULL ,
NAME VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Records of DIVISION
-- ----------------------------
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('2', 'Volzhskiy');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('3', 'Xinying');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('1', 'Baoluan');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('4', 'Jiangjiazui');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('5', 'Papetoai');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('6', 'Lonpao Dajah');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('7', 'Dailekh');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('8', 'Zaraza');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('9', 'Eybens');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('10', 'Lotoshino');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('11', 'Antalaha');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('12', 'Phutthaisong');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('13', 'Chaupimarca');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('14', 'Heilbronn');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('15', 'Qal‘eh-ye Khvājeh');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('16', 'Lityn');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('17', 'Trieste');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('18', 'Whittier');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('19', 'Baih');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('20', 'Lin’an');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('21', 'Opařany');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('22', 'Sulengwaseng');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('23', 'Felgueiras');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('24', 'Itinga');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('25', 'Clearwater');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('26', 'Wydminy');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('27', 'Stockholm');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('28', 'Huainan');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('29', 'Quva');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('30', 'Levallois-Perret');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('31', 'Eséka');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('32', 'Toulon');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('33', 'HanHuang');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('34', 'Knoxville');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('35', 'La Jagua de Ibirico');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('36', 'Longwood');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('37', 'Schiedam postbusnummers');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('38', 'Lanta Timur');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('39', 'Wailebe');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('40', 'Tempursari Wetan');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('41', 'Daqiao');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('42', 'Bontoc');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('43', 'Benito Juarez');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('44', 'Livramento do Brumado');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('45', 'Dougang');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('46', 'Wulongshan');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('47', 'Liljendal');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('48', 'Mlandizi');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('49', 'Suez');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('50', 'Palma De Mallorca');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('51', 'Kissónerga');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('52', 'Gentilly');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('53', 'Inuyama');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('54', 'Freiburg im Breisgau');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('55', 'Perches');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('56', 'Barrio San Luis');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('57', 'Totolan');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('58', 'San Juan Bautista');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('59', 'Comagascas');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('60', 'Al Ḩaffah');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('61', 'Tampa');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('62', 'Baru');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('63', 'Cayambe');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('64', 'Ochër');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('65', 'Capâo Bonito');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('66', 'La Cañada');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('67', 'Caen');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('68', 'Zicheng');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('69', 'Iksha');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('70', 'Rakhmanovo');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('71', 'Yaguarón');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('72', 'Surin');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('73', 'Narsingdi');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('74', 'Malá Strana');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('75', 'San Pedro de Atacama');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('76', 'Yoiqag');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('77', 'Nu’erbage');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('78', 'Novorossiysk');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('79', 'Bururi');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('80', 'Kudowa-Zdrój');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('81', 'Besançon');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('82', 'Eláteia');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('83', 'Jāndiāla Sher Khān');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('84', 'Kertasari');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('85', 'Jomboy');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('86', 'Tyazhinskiy');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('87', 'Tymbark');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('88', 'Sumbersewu');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('89', 'Trawniki');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('90', 'Apengjiang');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('91', 'Medalem');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('92', 'Karengan');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('93', 'Līvāni');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('94', 'Saint-Jean-de-Monts');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('95', 'Ivanava');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('96', 'Qingu');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('97', 'Krajan Dua Putukrejo');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('98', 'Torkanivka');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('99', 'Toledo');
INSERT INTO TRANSPORTMANAGEMENT.DIVISION VALUES ('100', 'Alcanena');

-- ----------------------------
-- Indexes structure for table DIVISION
-- ----------------------------

-- ----------------------------
-- Checks structure for table DIVISION
-- ----------------------------
ALTER TABLE TRANSPORTMANAGEMENT.DIVISION ADD CHECK (DIV_ID IS NOT NULL);
ALTER TABLE TRANSPORTMANAGEMENT.DIVISION ADD CHECK (NAME IS NOT NULL);
ALTER TABLE TRANSPORTMANAGEMENT.DIVISION ADD CHECK (Div_ID IS NOT NULL);
ALTER TABLE TRANSPORTMANAGEMENT.DIVISION ADD CHECK (Name IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table DIVISION
-- ----------------------------
ALTER TABLE TRANSPORTMANAGEMENT.DIVISION ADD PRIMARY KEY (DIV_ID);
