CREATE TABLE TRANSPORTMANAGEMENT.DBUser (
Username VARCHAR2(255 BYTE) NOT NULL ,
Password VARCHAR2(255 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE
;


INSERT INTO TRANSPORTMANAGEMENT.DBUser VALUES ('admin', 'admin');
INSERT INTO TRANSPORTMANAGEMENT.DBUser VALUES ('Niloy', '1234');